settings:
  app_title: Albert API
  auth_key_max_expiration_days: 365
  playground_opengatellm_url: ${OPENGATELLM_URL}
  playground_default_model: ${PLAYGROUND_DEFAULT_MODEL}
  playground_theme_accent_color: indigo
  swagger_url: https://albert.api.etalab.gouv.fr/swagger
  reference_url: https://albert.api.etalab.gouv.fr/reference
  documentation_url: https://docs.opengatellm.org/docs
  playground_opengatellm_timeout: 300
