name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call: # Add this to make the workflow reusable
  workflow_dispatch: # Add this to allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: npm
#          cache-dependency-path: ./docs/package-lock.json
#
#      - name: Install dependencies
#        working-directory: ./docs
#        run: npm ci
#
#      - name: Build Docusaurus site
#        working-directory: ./docs
#        run: npm run build
#
#      - name: Create CNAME file
#        working-directory: ./docs/build
#        run: echo "docs.opengatellm.etalab.gouv.fr" > CNAME
#
#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./docs/build
#          publish_branch: gh-pages
#          user_name: 'github-actions[bot]'
#          user_email: 'github-actions[bot]@users.noreply.github.com'
#
#  dns:
#    runs-on: ubuntu-latest
#
#    env:
#      OVH_APP_KEY: ${{ secrets.OVH_APP_KEY }}
#      OVH_APP_SECRET: ${{ secrets.OVH_APP_SECRET }}
#      OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Configure Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.12'
#
#      - name: Install dependencies
#        run: pip install ovh
#
#      - name: Run DNS management script
#        run: python scripts/manage_docs_dns.py
